<?php

namespace App\Facades;

class ExtendedDB extends \Illuminate\Support\Facades\DB
{
    public static function transaction(\Closure $callback, int $attempts = 1): mixed
    {
        parent::transaction($callback, $attempts); // TODO: Change the autogenerated stub
    }
}

